### PR TITLE
Fixed StackOverflowError while updating neighbour blocks.

### LINKED ISSUE #382: Crash (StackOverflowException) with 2 tunnels and 2 compact machines directly interacting (Tested with EnderIO)
**Compact Machines version**: 1.12.2-3.0.15-b249
**Forge version**: forge-14.23.5.2825
**I am not using Optifine**: Optifine is NOT installed
**Link to Crashlog**: I didn't think I'd need this as it's very easy to reproduce and it's partly shown in the video. It got deleted when I deleted the Twitch profile. If needed, I can just cause the crash again and get another one, just ask.
**Screenshot (if possible)**: Not necessary as I included a video.

**Description of the problem:**
Placing a compact machine next to another compact machine, and both compact machines have 2 tunnels in such a way where the 2 machines interact: using EnderIO cables inside both machines will crash the game with a StackOverflow exception while updating neighbor blocks. It is most likely some kind of infinite loop where one compact machines notifies the other and then that one responds by notifying the other over and over until it crashes.

**Expected Behavior:**
The game should continue to run without crashing.

**Actual Behavior:**
The game crashes and the world will crash the game every time you load it. You have to load a backup or use MCEdit to move one of the compact machines somewhere else.

**Steps to reproduce:**
I recorded a video on how to reproduce it. This includes installing the mods on the Twitch Launcher all the way until the crash and shows some of the crashlog. [Video Link](https://www.youtube.com/watch?v=KTuiuGS-C6o)

**Extra Notes:**
This may be a bug with EnderIO but even if it is, there should be some kind of handler for this kind of issue in the Compact Machines for future compatibility. (Such as sending a chat message like "Hey there was an error with Compact Machines! Please make a github issue with the logs/compactmachinescrash.log file" or something like that)

Keep in mind that I've only tested this issue with EnderIO, other mods or even vanilla blocks could potentially have the same issue.

### PR DESCRIPTION
**Pull request by HumanGamer**
Fixed #382

### CODE REVIEW

**Comment by HumanGamer** [comment]
@thraaawn Any update regarding having this merged?

**Comment by davenonymous** [comment]
I will take a closer look this weekend/tomorrow. Want to fix a few things and push a new release on sat/sun.
Any particular reason to use the block update tick instead of the tile entity update tick?

**Comment by HumanGamer** [comment]
> I will take a closer look this weekend/tomorrow. Want to fix a few things and push a new release on sat/sun.
> Any particular reason to use the block update tick instead of the tile entity update tick?

Not really, I could've used either. Just didn't think of it at the time as I was looking at the Block file.

**Comment by HumanGamer** [comment]
Closing as it's been fixed.

**Pull request closed without merging**
